name = "ElRaphik_Modpack"
description = "A curated collection of mods to enhance your REPO gameplay experience, mostly used for my friends and I."
version = "1.0.4"
website_url = "https://github.com/ElRaphik/Repo-modpacks"
contains_nsfw_content = false
package_type = "modpack"
communities = [ "repo",]
categories = [ "modpacks",]

[dependencies]
Traktool-SharedUpgrades = "*"
BepInEx-BepInExPack = "*"
Tansinator-Map_Value_Tracker = "*"
Zehs-ExtractionPointConfirmButton = "*"
Zehs-REPOLib = "*"
WhalesAllAround-MikuMikuBeamer = "*"
khalliv-GambleInShop = "*"
GarStudios-Oiia_Cat_Valuable = "*"
Rebateman-LateJoin = "*"
XiaohaiMod-XH_DamageShow_EnemyHealthBar = "*"
eth9n-Mimic = "*"
nickklmao-MenuLib = "*"
nickklmao-REPOConfig = "*"
linkoid-DreadHeadDuck = "*"
loaforc-loaforcsSoundAPI_REPO = "*"
loaforc-loaforcsSoundAPI = "*"
Tolian-REPODiscordRichPresence = "*"
JacuJ-GnomedGnomeSounds = "*"
Eteli-Fart_Grenade = "*"
Eteli-Fart_Mine = "*"
flipf17-DeadTTS = "*"
Zehs-LethalCompanyValuables = "*"
Godji-UltimateRevive = "*"
Gassayping-MemeSounds = "*"
Sai-CANNON = "*"
surfknasen-Walkie_Talkies = "*"
MTS-PostLevelSummaryPlus = "*"
kekprod-Bigger_Cart = "*"
PandaSquad-BetterSprint = "*"
AriIcedT-MinecraftStrongholdLevel = "*"
Rangerbb275-Hospital_Level = "*"
YMC_MHZ-MoreHead = "*"
GreatColtini-MinecraftAdditions = "*"
Juisader-MinecraftCosmetics = "*"
Cripplega-MikuAmenoReplaceLobby = "*"
Patrick-MapVote = "*"
dig-REPOPresents = "*"
XiaohaiMod-DroneBoomBox = "*"
ZeroTails-ExtraMusicforDroneBoomBox = "*"
Alya-MusicFromDroneBox = "*"
AxonPhantoms-ExtraMusicforDroneBoomBoxAxon = "*"
Ladlemods-LadlesExtraMusicforDroneBoomBox = "*"
OrtonLongGaming-FNAFLevel = "*"
ironbean-LevelNumberUI = "*"
x753_REPO-CustomColors = "*"
Rudeus-Vacuum_Enemy = "*"
