[config]
schemaVersion = "0.0.1"

[package]
namespace = "ElRaphik"
name = "ElRaphik_Modpack"
versionNumber = "1.1.0"
description = "A curated collection of mods to enhance your REPO gameplay experience, mostly used for my friends and I."
website_url = "https://github.com/ElRaphik/Repo-modpacks"
containsNsfwContent = false

[publish]
repository = "https://thunderstore.io"
communities = [ "repo",]

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"
[[build.copy]]
source = "./"
target = ""

[package.dependencies]
Alya-MusicFromDroneBox = "1.0.2"
AriIcedT-MinecraftStrongholdLevel = "1.6.1"
AxonPhantoms-ExtraMusicforDroneBoomBoxAxon = "1.0.0"
BepInEx-BepInExPack = "5.4.2100"
Cripplega-MikuAmenoReplaceLobby = "1.1.1"
Eteli-Fart_Grenade = "1.0.0"
Eteli-Fart_Mine = "1.0.0"
GarStudios-Oiia_Cat_Valuable = "1.0.0"
Gassayping-MemeSounds = "1.3.0"
Godji-UltimateRevive = "1.0.1"
GreatColtini-MinecraftAdditions = "1.0.7"
JacuJ-GnomedGnomeSounds = "1.0.0"
Juisader-MinecraftCosmetics = "0.0.6"
Ladlemods-LadlesExtraMusicforDroneBoomBox = "3.0.0"
MTS-PostLevelSummaryPlus = "1.1.0"
OrtonLongGaming-FNAFLevel = "1.0.3"
PandaSquad-BetterSprint = "2.0.0"
Patrick-MapVote = "1.1.0"
Rangerbb275-Hospital_Level = "2.0.0"
Rebateman-LateJoin = "0.1.2"
Rudeus-Vacuum_Enemy = "1.0.13"
Sai-CANNON = "0.8.6"
Tansinator-Map_Value_Tracker = "1.2.2"
Tolian-REPODiscordRichPresence = "0.1.6"
Traktool-SharedUpgrades = "2.1.3"
WhalesAllAround-MikuMikuBeamer = "1.0.1"
XiaohaiMod-DroneBoomBox = "1.0.0"
XiaohaiMod-XH_DamageShow_EnemyHealthBar = "1.0.2"
YMC_MHZ-MoreHead = "1.4.0"
Zehs-ExtractionPointConfirmButton = "1.1.0"
Zehs-LethalCompanyValuables = "1.2.1"
Zehs-REPOLib = "2.1.0"
ZeroTails-ExtraMusicforDroneBoomBox = "1.0.8"
dig-REPOPresents = "1.3.0"
eth9n-Mimic = "1.1.6"
flipf17-DeadTTS = "1.0.10"
ironbean-LevelNumberUI = "1.0.0"
kekprod-Bigger_Cart = "1.0.6"
khalliv-GambleInShop = "1.0.0"
linkoid-DreadHeadDuck = "1.0.0"
loaforc-loaforcsSoundAPI = "2.0.6"
loaforc-loaforcsSoundAPI_REPO = "1.0.1"
nickklmao-MenuLib = "2.4.1"
nickklmao-REPOConfig = "1.2.2"
surfknasen-Walkie_Talkies = "1.1.2"
x753_REPO-CustomColors = "1.1.1"

[publish.categories]
repo = [ "modpacks",]
