name = "MyREPOModpack"
description = "A curated collection of mods to enhance your REPO gameplay experience."
version = "1.0.0"
website_url = "https://github.com/ElRaphik/Repo-modpacks"
contains_nsfw_content = false
package_type = "modpack"
icon = "icon.png"
readme = "README.md"
communities = ["repo"]
categories = ["modpacks"]

[dependencies]
"cooldev-AmazingMod" = "*"
"proplayer-GameplayTweaks" = "*"
"thebest-ModEnhancer" = "*"