name: Update Modpack Dependencies

on:
  schedule:
    - cron: '0 5 * * *'  # every day at 5 AM UTC
  workflow_dispatch:      # allow manual run if needed

permissions:
  contents: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python libraries
        run: |
          pip install requests packaging

      - name: Run dependency updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python update_dependencies.py

      - name: Commit and push changes
        if: success()  # Only commit if update script ran successfully
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add manifest.json
          git diff --cached --quiet || git commit -m "chore: update dependencies automatically"
          git push
